### ISSUE TITLE
Firmware OTA

### ISSUE THREAD

**Issue by roccomuso** [amiravni/ESP8266_12VLEDS_Websocket_OTA#1]
Where's in the code the part relative to the Over the Air updates?

**Comment by amiravni** [comment]
it's the HTTPUpdateConnect() function
I've tried to describe it a bit more on my blog
http://www.whatimade.today/esp8266-on-websockets-mdns-ota-and-leds/

There's a section there on the OTA ("Over-The-Air(OTA) Code Updates")
