### ISSUE TITLE
Not compiling

### ISSUE THREAD

**Issue by andreaguiar** [amiravni/ESP8266_12VLEDS_Websocket_OTA#2]
Hi Amir,
First and foremost, congrats on the very nice project and tutorial you build, really what I was looking for. ;)

So, when I try to compile the LedStrip12V.ino I get an error:

> C:\Users\André\Documents\Arduino\libraries\WebSockets\src\WebSocketsClient.cpp: In member function 'void WebSocketsClient::begin(const char_, uint16_t, const char_, const char*)':
> 
>  C:\Users\André\Documents\Arduino\libraries\WebSockets\src\WebSocketsClient.cpp:63:16: error: 'RANDOM_REG32' was not declared in this scope
> 
>  randomSeed(RANDOM_REG32);
> 
>  ^
> 
>  exit status 1
>  Error compiling.

Any idea...?

**Comment by andreaguiar** [comment]
Solved...

**Comment by amiravni** [comment]
Cool! What was the problem?

**Comment by andreaguiar** [comment]
I don't know... I just uninstalled Arduino and eliminated every library and it worked...

**Comment by amiravni** [comment]
Ah! Best solution! :)
Feel free to upload some photos/videos to our comment section in the blog when you're done!

**Comment by andreaguiar** [comment]
Will do ;)

**Comment by andreaguiar** [comment]
Hi Amir
I'm trying to understand your code...
What would you change in order to change the color at which the rainbow starts when I power the esp8266?

**Comment by amiravni** [comment]
line 34 on the .ino is the one controlling the color wheel

```
writeWheel(cnt++, RGB);
```

just init "cnt" to be something other than zero and it will start with a different color

**Comment by andreaguiar** [comment]
Ok thanks I will try that.

**Comment by andreaguiar** [comment]
Hey Amir, I forgot to tell you, at the beginning I was having a hard time figuring how to get the web page working, I was using Chrome, and nothing showed up in the browser... but then I tried with Firefox and it works perfectly, even with IE and Edge, but not with Chrome...

**Comment by amiravni** [comment]
That's interesting, especially since Chrome was the first browser which supported Web-sockets - perhaps it was disabled somehow.

**Comment by andreaguiar** [comment]
When I delete the src or the lib files, it opens with Chrome and the controls work fine.

**Comment by amiravni** [comment]
Hi, 
The code didn't work with Chrome because of an update in Chrome security issues.
I've solved it and it should work now.

**Comment by andreaguiar** [comment]
Perfect! Thanks
